---

- hosts: tomcat
  
  tasks:
  - name: Stoping tomcat
    service: name=tomcat7 state=stopped

  - name: remove war file
    shell: rm -rf {{ destination }}/*

  - copy:
      src: "{{ warRemotePath }}"
      dest: "{{ destination }}" 

  - name: restarting service 
    service: name=tomcat7 state=restarted

